Repository iterative/scmrepo, pull requests merged in 2022-05, with the labels that each got.

#62 dulwich: handle invalid revisions in diff
  scmrepo/git/backend/dulwich/__init__.py
Labels: bug

#76 use setuptools_scm
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  pyproject.toml
  setup.cfg
Labels: enhancement

#82 objects: don't recompute object size
  scmrepo/git/backend/dulwich/__init__.py
  scmrepo/git/backend/pygit2.py
Labels: performance
